config/routes.rb
Rails.application.routes.draw do
  resources :notadeaulas

end

app/models/notadeaula.rb
class Notadeaula < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notadeaulas_controller.rb
class NotadeaulasController < ApplicationController
  before_action :set_notadeaula, only: [:show, :edit, :update, :destroy]

  # GET /notadeaulas
  # GET /notadeaulas.json
  def index
    @notadeaulas = Notadeaula.all
  end

  # GET /notadeaulas/1
  # GET /notadeaulas/1.json
  def show
  end

  # GET /notadeaulas/new
  def new
    @notadeaula = Notadeaula.new
  end

  # GET /notadeaulas/1/edit
  def edit
  end

  # POST /notadeaulas
  # POST /notadeaulas.json
  def create
    @notadeaula = Notadeaula.new(notadeaula_params)

    respond_to do |format|
      if @notadeaula.save
        format.html { redirect_to @notadeaula, notice: 'Notadeaula was successfully created.' }
        format.json { render :show, status: :created, location: @notadeaula }
      else
        format.html { render :new }
        format.json { render json: @notadeaula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notadeaulas/1
  # PATCH/PUT /notadeaulas/1.json
  def update
    respond_to do |format|
      if @notadeaula.update(notadeaula_params)
        format.html { redirect_to @notadeaula, notice: 'Notadeaula was successfully updated.' }
        format.json { render :show, status: :ok, location: @notadeaula }
      else
        format.html { render :edit }
        format.json { render json: @notadeaula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notadeaulas/1
  # DELETE /notadeaulas/1.json
  def destroy
    @notadeaula.destroy
    respond_to do |format|
      format.html { redirect_to notadeaulas_url, notice: 'Notadeaula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notadeaula
      @notadeaula = Notadeaula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notadeaula_params
      params.require(:notadeaula).permit(:autor, :disciplina, :ano, :semestre, :data, :titulo, :texto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notadeaulas_helper.rb
module NotadeaulasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meuapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notadeaulas/_form.html.erb
<%= form_for(@notadeaula) do |f| %>
  <% if @notadeaula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notadeaula.errors.count, "error") %> prohibited this notadeaula from being saved:</h2>

      <ul>
      <% @notadeaula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :disciplina %><br>
    <%= f.text_field :disciplina %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :semestre %><br>
    <%= f.number_field :semestre %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_area :texto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notadeaulas/edit.html.erb
<h1>Editing notadeaula</h1>

<%= render 'form' %>

<%= link_to 'Show', @notadeaula %> |
<%= link_to 'Back', notadeaulas_path %>

app/views/notadeaulas/index.html.erb
<h1>Listing notadeaulas</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Disciplina</th>
      <th>Ano</th>
      <th>Semestre</th>
      <th>Data</th>
      <th>Titulo</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notadeaulas.each do |notadeaula| %>
      <tr>
        <td><%= notadeaula.autor %></td>
        <td><%= notadeaula.disciplina %></td>
        <td><%= notadeaula.ano %></td>
        <td><%= notadeaula.semestre %></td>
        <td><%= notadeaula.data %></td>
        <td><%= notadeaula.titulo %></td>
        <td><%= notadeaula.texto %></td>
        <td><%= link_to 'Show', notadeaula %></td>
        <td><%= link_to 'Edit', edit_notadeaula_path(notadeaula) %></td>
        <td><%= link_to 'Destroy', notadeaula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notadeaula', new_notadeaula_path %>

app/views/notadeaulas/new.html.erb
<h1>New notadeaula</h1>

<%= render 'form' %>

<%= link_to 'Back', notadeaulas_path %>

app/views/notadeaulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @notadeaula.autor %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @notadeaula.disciplina %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @notadeaula.ano %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @notadeaula.semestre %>
</p>

<p>
  <strong>Data:</strong>
  <%= @notadeaula.data %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @notadeaula.titulo %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @notadeaula.texto %>
</p>

<%= link_to 'Edit', edit_notadeaula_path(@notadeaula) %> |
<%= link_to 'Back', notadeaulas_path %>